module.exports = [
  {
    key: 'first_door',
    title: 'First Door',
    description: 'Unlock your very first door.',
    icon: 'door-open',
    criteria: { type: 'doors_completed', threshold: 1 },
    xpBonus: 50,
  },
  {
    key: 'key_master',
    title: 'Key Master',
    description: 'Collect 25 keys across all doors.',
    icon: 'key',
    criteria: { type: 'keys_collected', threshold: 25 },
    xpBonus: 100,
  },
  {
    key: 'seven_day_streak',
    title: '7 Day Streak',
    description: 'Solve at least one door every day for 7 days in a row.',
    icon: 'flame',
    criteria: { type: 'streak', threshold: 7 },
    xpBonus: 200,
  },
  {
    key: 'array_master',
    title: 'Array Master',
    description: 'Complete all doors in World 1 — Arrays.',
    icon: 'grid',
    criteria: { type: 'topic_mastery', threshold: 15, topic: 'Arrays' },
    xpBonus: 150,
  },
  {
    key: 'binary_search_warrior',
    title: 'Binary Search Warrior',
    description: 'Complete all doors in World 5 — Binary Search.',
    icon: 'search',
    criteria: { type: 'topic_mastery', threshold: 8, topic: 'Binary Search' },
    xpBonus: 150,
  },
  {
    key: 'tree_master',
    title: 'Tree Master',
    description: 'Complete all doors in World 9 — Trees & BST.',
    icon: 'git-branch',
    criteria: { type: 'topic_mastery', threshold: 12, topic: 'Trees & BST' },
    xpBonus: 200,
  },
  {
    key: 'graph_explorer',
    title: 'Graph Explorer',
    description: 'Complete all doors in World 10 — Graphs.',
    icon: 'share-2',
    criteria: { type: 'topic_mastery', threshold: 10, topic: 'Graphs' },
    xpBonus: 200,
  },
  {
    key: 'final_boss_slayer',
    title: 'Final Boss Slayer',
    description: 'Defeat Door 100, the final boss.',
    icon: 'sword',
    criteria: { type: 'boss_defeated', threshold: 100 },
    xpBonus: 500,
  },
  {
    key: 'hundred_doors_completed',
    title: '100 Doors Completed',
    description: 'Complete all 100 doors of the dungeon.',
    icon: 'crown',
    criteria: { type: 'doors_completed', threshold: 100 },
    xpBonus: 1000,
  },
];
